services:
  avatar-backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend/storage:/app/storage
      - ./backend/prisma/storage:/app/prisma/storage
      - ./backend/settings.yaml:/app/settings.yaml
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./prisma/storage/database.sqlite
      - CONFIG_PATH=./settings.yaml
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

