app:
  storage:
    type: 'local'
    local:
      save_path: './storage/test-avatars'
  server:
    port: 3002 # Отдельный порт для тестов
  database:
    driver: 'sqlite'
    connection:
      maxRetries: 1 # Минимальное количество попыток для быстрых тестов
      retryDelay: 100 # Минимальная задержка
    sqlite_params:
      url: 'file::memory:' # In-memory база данных для тестов
