app:
  storage:
    type: 'local'
    local:
      save_path: './storage/avatars'
  
  # Кеширование включено но не используется (no-op стратегия)
  cache:
    type: 'disabled'
  
  server:
    host: '0.0.0.0'
    port: 3000
  
  database:
    driver: 'sqlite'
    sqlite_params:
      url: 'file:./storage/database/database.sqlite'
  
  logging:
    level: 'info'
    verbose: false
    pretty: true
