app:
  server:
    host: "0.0.0.0"
    port: 8080  # Стандартный порт для продакшена
  database:
    connection:
      maxRetries: 3  # Стандартное количество попыток
      retryDelay: 3000  # Больше задержка для продакшена
    sqlite_params:
      url: "file:./storage/database/database.sqlite"  # Продакшен БД
  logging:
    level: "warn"  # только предупреждения и ошибки в продакшене
    verbose: false  # отключить детальное логирование
    pretty: false  # JSON формат для продакшена
