app:
  storage:
    type: 's3' # используем S3 для production
    s3:
      endpoint: 'https://your-s3-endpoint.com'
      bucket: 'your-bucket-name'
      access_key: 'YOUR_S3_ACCESS_KEY'
      secret_key: 'YOUR_S3_SECRET_KEY'
      region: 'us-east-1'
      force_path_style: true
      connection:
        maxRetries: 3
        retryDelay: 3000
  server:
    host: '0.0.0.0'
    port: 3000 # Стандартный порт для backend API
  database:
    driver: 'postgresql' # PostgreSQL для production
    connection:
      maxRetries: 3 # Стандартное количество попыток
      retryDelay: 3000 # Больше задержка для продакшена
    network:
      host: 'postgres' # имя сервиса в docker-compose
      port: 5432
      database: 'avatar_gen'
      username: 'postgres'
      password: 'password'
      ssl: false
  logging:
    level: 'warn' # только предупреждения и ошибки в продакшене
    verbose: false # отключить детальное логирование
    pretty: false # JSON формат для продакшена
