app:
  storage:
    type: 's3' # используем s3 для разработки
    s3:
      endpoint: 'https://your-s3-endpoint.com'
      bucket: 'your-bucket-name'
      access_key: 'YOUR_S3_ACCESS_KEY'
      secret_key: 'YOUR_S3_SECRET_KEY'
      region: 'us-east-1'
      force_path_style: true
      connection:
        maxRetries: 5
        retryDelay: 1000
  server:
    port: 3001 # Разный порт для разработки
  database:
    driver: 'sqlite' # Используем SQLite для разработки
    # В разработке можно использовать более детальное логирование подключений
    connection:
      maxRetries: 5 # Больше попыток для разработки
      retryDelay: 1000 # Меньше задержка между попытками
    sqlite_params:
      url: 'file:./backend/storage/database/database.dev.sqlite' # Отдельная БД для разработки
  logging:
    level: 'debug'
    verbose: true
    pretty: true
