# Пример файла настроек для тестирования
# Скопируйте этот файл в settings.test.yaml и настройте под свои нужды

app:
  storage:
    type: 's3'  # 'local' или 's3'
    local:
      save_path: './storage/test-avatars'
    s3:
      # Используйте переменные окружения для безопасного хранения credentials
      endpoint: '${TEST_S3_ENDPOINT:-https://s3.amazonaws.com}'
      bucket: '${TEST_S3_BUCKET:-avatar-gen-test}'
      access_key: '${TEST_S3_ACCESS_KEY:-your-test-access-key}'
      secret_key: '${TEST_S3_SECRET_KEY:-your-test-secret-key}'
      region: '${TEST_S3_REGION:-us-east-1}'
      force_path_style: true
      connection:
        maxRetries: 3
        retryDelay: 1000

  server:
    port: 3002  # Отдельный порт для тестов

  database:
    driver: 'sqlite'  # 'sqlite' или 'postgresql'
    connection:
      maxRetries: 3
      retryDelay: 1000
    sqlite_params:
      url: 'file:./storage/test-database/database.test.sqlite'
    network:
      host: 'localhost'
      port: 5432
      database: 'avatar_gen_test'
      username: 'postgres'
      password: 'password'
      ssl: false

  logging:
    level: 'error'  # 'debug', 'info', 'warn', 'error'
    verbose: false
    pretty: false

# Примеры переменных окружения для локального тестирования:
# export TEST_S3_ENDPOINT=https://s3.amazonaws.com
# export TEST_S3_BUCKET=your-test-bucket
# export TEST_S3_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
# export TEST_S3_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
# export TEST_S3_REGION=us-east-1
