name: Unit Tests

on:
  # Ручной запуск
  workflow_dispatch:
    inputs:
      config_type:
        description: 'Тип конфигурации для тестов'
        required: false
        default: 'unit'
        type: choice
        options:
          - unit
          - default

  # Запуск при изменении unit тестов
  push:
    paths:
      - 'backend/src/**/*.spec.ts'
      - 'backend/src/**/*.test.ts'
      - 'backend/configs/settings.test.unit.yaml'
      - 'backend/vitest.config.ts'

  # Запуск при PR в develop
  pull_request:
    branches:
      - develop
    paths:
      - 'backend/src/**/*.spec.ts'
      - 'backend/src/**/*.test.ts'
      - 'backend/configs/settings.test.unit.yaml'

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '10'

jobs:
  unit-tests:
    name: Unit Tests (${{ github.event.inputs.config_type || 'unit' }})
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run unit tests with Docker Compose
        run: |
          # Определяем конфигурацию для тестов
          if [ "${{ github.event.inputs.config_type || 'unit' }}" = "unit" ]; then
            CONFIG_FILE="settings.test.unit.yaml"
          else
            CONFIG_FILE="settings.test.yaml"
          fi

          echo "🧪 Запуск unit тестов с конфигурацией: $CONFIG_FILE"

          # Запускаем unit тесты с монтированием нужной конфигурации
          docker compose -f docker/docker-compose.test-extended.yaml --profile unit-only up --build --abort-on-container-exit avatar-backend-unit

          echo "✅ Unit тесты завершены"

      - name: Collect test results
        if: always()
        run: |
          echo "📊 Сбор результатов unit тестов..."
          docker compose -f docker/docker-compose.test-extended.yaml logs avatar-backend-unit > unit-test-results.log

          echo "## 🧪 Unit Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Configuration Used" >> $GITHUB_STEP_SUMMARY
          echo "- Config: ${{ github.event.inputs.config_type || 'unit' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Database: SQLite (in-memory)" >> $GITHUB_STEP_SUMMARY
          echo "- Storage: Local filesystem" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ -f unit-test-results.log ]; then
            echo "### Test Output" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            tail -50 unit-test-results.log >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: unit-test-results.log
          retention-days: 7

      - name: Cleanup
        if: always()
        run: |
          echo "🧹 Очистка ресурсов..."
          docker compose -f docker/docker-compose.test-extended.yaml --profile unit-only down --remove-orphans
