name: avatar-gen-test

services:
  # MinIO для имитации S3 в тестовой среде
  minio:
    image: minio/minio:latest
    container_name: avatar-gen-minio-test
    profiles:
      - s3-storage
      - integration-tests
      - e2e-tests
    environment:
      MINIO_ROOT_USER: test-access-key
      MINIO_ROOT_PASSWORD: test-secret-key
      MINIO_DEFAULT_BUCKETS: avatar-gen-test
    ports:
      - '9000:9000' # MinIO API
      - '9001:9001' # MinIO Console
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - test-internal

  # PostgreSQL для тестов (временный контейнер)
  postgres-test:
    image: postgres:17-alpine
    container_name: avatar-gen-postgres-test
    profiles:
      - postgres-only # Для standalone запуска PostgreSQL
      - postgresql-storage
      - integration-tests
      - e2e-tests
    environment:
      POSTGRES_DB: avatar_gen_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    ports:
      - '5433:5432' # Другой порт для тестов
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U test_user -d avatar_gen_test']
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - test-internal
    # Автоматическое удаление при остановке
    restart: 'no'

  # Backend для Unit тестов (SQLite + Local Storage)
  avatar-backend-unit:
    build:
      context: ../backend
      dockerfile: docker/Dockerfile
    container_name: avatar-gen-backend-unit-test
    profiles:
      - unit-tests
    volumes:
      - ../backend/configs/settings.test.yaml:/app/settings.yaml:ro
      - ../backend/logs:/app/logs
      - test_storage:/app/storage
    environment:
      - NODE_ENV=test
      - CONFIG_PATH=./settings.yaml
    command: ['npm', 'run', 'test:unit']
    networks:
      - test-internal

  # Backend для Integration тестов (PostgreSQL + MinIO)
  avatar-backend-integration:
    build:
      context: ../backend
      dockerfile: docker/Dockerfile
    container_name: avatar-gen-backend-integration-test
    profiles:
      - integration-tests
    depends_on:
      postgres-test:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - ../backend/configs/settings.test.yaml:/app/settings.yaml:ro
      - ../backend/logs:/app/logs
    environment:
      - NODE_ENV=test
      - CONFIG_PATH=./settings.yaml
      - TEST_S3_ENDPOINT=http://minio:9000
      - TEST_S3_BUCKET=avatar-gen-test
      - TEST_S3_ACCESS_KEY=test-access-key
      - TEST_S3_SECRET_KEY=test-secret-key
      - TEST_S3_REGION=us-east-1
      - TEST_DB_HOST=postgres-test
      - TEST_DB_PORT=5432
      - TEST_DB_NAME=avatar_gen_test
      - TEST_DB_USER=test_user
      - TEST_DB_PASSWORD=test_password
    command: ['npm', 'run', 'test:integration']
    networks:
      - test-internal

  # Backend для E2E тестов (PostgreSQL + MinIO + Frontend)
  avatar-backend-e2e:
    build:
      context: ../backend
      dockerfile: docker/Dockerfile
    container_name: avatar-gen-backend-e2e-test
    profiles:
      - e2e-tests
    depends_on:
      postgres-test:
        condition: service_healthy
      minio:
        condition: service_healthy
    expose:
      - '3000'
    volumes:
      - ../backend/configs/settings.test.yaml:/app/settings.yaml:ro
      - ../backend/logs:/app/logs
    environment:
      - NODE_ENV=test
      - CONFIG_PATH=./settings.yaml
      - TEST_S3_ENDPOINT=http://minio:9000
      - TEST_S3_BUCKET=avatar-gen-test
      - TEST_S3_ACCESS_KEY=test-access-key
      - TEST_S3_SECRET_KEY=test-secret-key
      - TEST_S3_REGION=us-east-1
      - TEST_DB_HOST=postgres-test
      - TEST_DB_PORT=5432
      - TEST_DB_NAME=avatar_gen_test
      - TEST_DB_USER=test_user
      - TEST_DB_PASSWORD=test_password
    networks:
      - test-internal

  # Frontend для E2E тестов
  avatar-frontend-e2e:
    build:
      context: ../frontend
      dockerfile: docker/Dockerfile
    container_name: avatar-gen-frontend-e2e-test
    profiles:
      - e2e-tests
    depends_on:
      - avatar-backend-e2e
    expose:
      - '8080'
    volumes:
      - ../frontend/logs:/var/log/nginx
    environment:
      - NODE_ENV=test
      - VITE_API_URL=http://avatar-backend-e2e:3000
    networks:
      - test-internal

  # Gateway для E2E тестов
  gateway-e2e:
    build:
      context: ../gateway
      dockerfile: Dockerfile
    container_name: avatar-gen-gateway-e2e-test
    profiles:
      - e2e-tests
    depends_on:
      - avatar-frontend-e2e
      - avatar-backend-e2e
    ports:
      - '12746:12745' # Другой порт для тестов
    volumes:
      - ../gateway/configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../gateway/configs/static:/usr/share/nginx/html/static:ro
      - ../gateway/logs:/var/log/nginx
    networks:
      - test-internal

  # Test Runner для матричного тестирования
  test-runner:
    build:
      context: ../backend
      dockerfile: docker/Dockerfile
    container_name: avatar-gen-test-runner
    profiles:
      - matrix-tests
    volumes:
      - ../backend:/app
      - ../backend/logs:/app/logs
      - test_storage:/app/storage
    environment:
      - NODE_ENV=test
    command: ['npm', 'run', 'test:matrix']
    networks:
      - test-internal

volumes:
  postgres_test_data:
    driver: local
  minio_data:
    driver: local
  test_storage:
    driver: local

networks:
  test-internal:
    driver: bridge
    internal: false
    name: avatar-gen-test-internal
