# Docker Compose конфигурация с S3 хранилищем
#
# Использование:
#   docker compose -f docker-compose.yml -f docker-compose.s3.yml up -d
#
# Этот файл переопределяет конфигурацию для использования S3 вместо локального хранилища

services:
  avatar-backend:
    environment:
      # Переопределяем тип хранилища на S3
      - STORAGE_TYPE=s3
      # S3 Configuration (установите ваши значения)
      - S3_ENDPOINT=${S3_ENDPOINT:-https://your-s3-endpoint.com}
      - S3_BUCKET=${S3_BUCKET}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_REGION=${S3_REGION:-us-east-1}
      - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE:-true}
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    volumes:
      # Убираем монтирование локального storage (не нужен для S3)
      - ../backend/settings.yaml:/app/settings.yaml:ro
      - ../backend/settings.production.yaml:/app/settings.production.yaml:ro
      - ../backend/logs:/app/logs
      # storage не монтируется - используется S3
