import type { Plugin } from 'vite';
import { readdirSync, statSync, readFileSync } from 'fs';
import { join, relative, sep } from 'path';

/**
 * Рекурсивно находит все директории locales в проекте
 */
function findLocalesDirectories(dir: string, results: string[] = []): string[] {
  try {
    const files = readdirSync(dir);

    for (const file of files) {
      const filePath = join(dir, file);
      const stat = statSync(filePath);

      if (stat.isDirectory()) {
        if (file === 'locales') {
          results.push(filePath);
        } else if (file !== 'node_modules' && file !== 'dist' && file !== '.git') {
          findLocalesDirectories(filePath, results);
        }
      }
    }
  } catch {
    // Игнорируем ошибки доступа к директориям
  }

  return results;
}

/**
 * Определяет namespace из пути к директории locales
 */
function getNamespaceFromPath(localesPath: string, srcPath: string): string {
  const relativePath = relative(srcPath, localesPath);
  const parts = relativePath.split(sep);

  // Убираем последний элемент (locales) и shared
  const filteredParts = parts.slice(0, -1).filter(part => part !== 'shared');

  if (filteredParts.length === 0) {
    return 'translation';
  }

  // Преобразуем путь в camelCase namespace
  // Например: features/avatar-link-copy -> featuresAvatarLinkCopy
  const namespace = filteredParts
    .join('-')
    .split('-')
    .map((part, index) => (index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join('');

  return namespace;
}

/**
 * Собирает все переводы из JSON файлов
 */
function collectTranslations(localesDirs: string[], srcPath: string) {
  const translations: Record<string, Record<string, Record<string, unknown>>> = {};
  const supportedLanguages = new Set<string>();

  for (const localesDir of localesDirs) {
    const namespace = getNamespaceFromPath(localesDir, srcPath);

    try {
      const files = readdirSync(localesDir);

      for (const file of files) {
        if (file.endsWith('.json')) {
          const lang = file.replace('.json', '');
          supportedLanguages.add(lang);

          const filePath = join(localesDir, file);
          const content = readFileSync(filePath, 'utf-8');
          const data = JSON.parse(content);

          if (!translations[lang]) {
            translations[lang] = {};
          }

          translations[lang][namespace] = data;
        }
      }
    } catch (error) {
      console.error(`Error reading locales from ${localesDir}:`, error);
    }
  }

  return { translations, supportedLanguages: Array.from(supportedLanguages) };
}

/**
 * Vite плагин для автоматического сбора и объединения переводов
 */
export function i18nAutoImport(): Plugin {
  const virtualModuleId = 'virtual:i18n-resources';
  const resolvedVirtualModuleId = '\0' + virtualModuleId;

  let srcPath: string;
  let generatedCode: string;

  return {
    name: 'vite-plugin-i18n-auto-import',

    configResolved(config) {
      srcPath = join(config.root, 'src');
    },

    resolveId(id) {
      if (id === virtualModuleId) {
        return resolvedVirtualModuleId;
      }
    },

    load(id) {
      if (id === resolvedVirtualModuleId) {
        if (!generatedCode) {
          const localesDirs = findLocalesDirectories(srcPath);
          const { translations, supportedLanguages } = collectTranslations(localesDirs, srcPath);

          console.log(`\n🌐 i18n: Собрано ${localesDirs.length} директорий с переводами`);
          console.log(`   Языки: ${supportedLanguages.join(', ')}`);
          console.log(
            `   Namespaces: ${Object.keys(translations[supportedLanguages[0]] || {}).join(', ')}\n`,
          );

          // Генерируем код напрямую без JSON.stringify
          const translationsStr = JSON.stringify(translations, null, 2);
          const languagesStr = JSON.stringify(supportedLanguages);

          generatedCode = `// Auto-generated by vite-plugin-i18n-auto-import
export const i18nResources = ${translationsStr};
export const supportedLanguages = ${languagesStr};
`;
        }

        return generatedCode;
      }
    },

    async handleHotUpdate({ file, server, modules }) {
      // Проверяем, что это файл перевода
      if (file.includes('locales') && file.endsWith('.json')) {
        const fileName = file.split(/[/\\]locales[/\\]/)[1] || file;
        console.log(`\n🔄 HMR: Обновление переводов из ${fileName}`);

        // Сбрасываем кэш сгенерированного кода
        generatedCode = '';

        // Получаем виртуальный модуль
        const module = server.moduleGraph.getModuleById(resolvedVirtualModuleId);
        if (module) {
          // Инвалидируем модуль
          server.moduleGraph.invalidateModule(module);

          // Отправляем HMR событие всем импортерам
          const timestamp = Date.now();
          const hmrPayload = {
            type: 'update' as const,
            updates: [
              {
                type: 'js-update' as const,
                timestamp,
                path: virtualModuleId,
                acceptedPath: virtualModuleId,
              },
            ],
          };

          server.ws.send(hmrPayload);
          console.log('✅ HMR: Переводы обновлены');

          // Возвращаем массив модулей для дальнейшей обработки HMR
          return [module, ...modules];
        }

        return [];
      }
    },
  };
}
