app:
  storage:
    type: 'local'
    local:
      save_path: './storage/test-avatars'
    s3:
      endpoint: 'http://minio:9000'
      bucket: 'avatar-gen-test'
      access_key: 'test-access-key'
      secret_key: 'test-secret-key'
      region: 'us-east-1'
      force_path_style: true
      connection:
        maxRetries: 1
        retryDelay: 100
  server:
    port: 3000
  database:
    driver: 'postgresql'
    connection:
      maxRetries: 3
      retryDelay: 1000
    network:
      host: 'postgres-test'
      port: 5432
      database: 'avatar_gen_test'
      username: 'test_user'
      password: 'test_password'
      ssl: false
  logging:
    level: 'debug'
    verbose: true
    pretty: true

