app:
  storage:
    type: 'local'
    local:
      save_path: './storage/test-avatars'
    s3:
      endpoint: 'http://minio:9000'
      bucket: 'avatar-gen-test'
      access_key: 'test-access-key'
      secret_key: 'test-secret-key'
      region: 'us-east-1'
      force_path_style: true
      connection:
        maxRetries: 1
        retryDelay: 100
  server:
    host: '127.0.0.1'
    port: 3002
  database:
    driver: 'sqlite'
    connection:
      maxRetries: 1
      retryDelay: 100
    sqlite_params:
      url: 'file::memory:'
    network:
      host: 'localhost'
      port: 5432
      database: 'avatar_gen_test'
      username: 'test_user'
      password: 'test_password'
      ssl: false
  logging:
    level: 'error'
    verbose: false
    pretty: false
