app:
  storage:
    type: 's3'
    s3:
      endpoint: 'http://minio:9000'
      bucket: 'avatar-gen-test'
      access_key: 'test-access-key'
      secret_key: 'test-secret-key'
      region: 'us-east-1'
      force_path_style: true
      connection:
        maxRetries: 5
        retryDelay: 1000
  server:
    host: '0.0.0.0'
    port: 3000
  database:
    driver: 'postgresql'
    connection:
      maxRetries: 3
      retryDelay: 3000
    network:
      host: 'postgres'
      synchronize: true
      port: 5432
      database: 'avatar_gen'
      username: 'postgres'
      password: 'password'
      ssl: false
  logging:
    level: 'debug'
    verbose: true
    pretty: true
